# Generated by Django 6.0.5 on 2026-06-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hoverImages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
