import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'voltvibe_project.settings')
django.setup()

from api.models import Product

products_data = [
  {
    "id": "1",
    "name": "Samsung 55\" QLED 4K Smart TV Q80D",
    "brand": "Samsung",
    "category": "smart-tvs",
    "price": 189999,
    "originalPrice": 249000,
    "discount": 24,
    "rating": 4.4,
    "reviews": 1203,
    "image": "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isBestSeller": True,
    "isHot": False,
    "isNew": False,
  },
  {
    "id": "2",
    "name": "Sony WH-1000XM6 Wireless Headphones",
    "brand": "Sony",
    "category": "headphones",
    "price": 89999,
    "originalPrice": 115000,
    "discount": 22,
    "rating": 4.8,
    "reviews": 2456,
    "image": "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": True,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "3",
    "name": "Audionic Wolfpack TWS Earbuds",
    "brand": "Audionic",
    "category": "wireless-earbuds",
    "price": 4499,
    "originalPrice": 5999,
    "discount": 25,
    "rating": 4.2,
    "reviews": 822,
    "image": "https://images.unsplash.com/photo-1572569433114-6f3458cded74?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": False,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "4",
    "name": "Haier 1.5 Ton Inverter AC",
    "brand": "Haier",
    "category": "smart-home",
    "price": 115000,
    "originalPrice": 145000,
    "discount": 21,
    "rating": 4.3,
    "reviews": 567,
    "image": "https://images.unsplash.com/photo-1622201389860-245f7bd47413?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": False,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "5",
    "name": "Logitech MX Master 3S Mouse",
    "brand": "Logitech",
    "category": "keyboards",
    "price": 21500,
    "originalPrice": 27999,
    "discount": 23,
    "rating": 4.7,
    "reviews": 1834,
    "image": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isBestSeller": True,
    "isHot": False,
    "isNew": False,
  },
  {
    "id": "6",
    "name": "Canon EOS R50 Camera",
    "brand": "Canon",
    "category": "cameras",
    "price": 145000,
    "originalPrice": 185000,
    "discount": 22,
    "rating": 4.6,
    "reviews": 432,
    "image": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isNew": True,
    "isHot": False,
    "isBestSeller": False,
  },
  {
    "id": "7",
    "name": "JBL Charge 5 Portable Speaker",
    "brand": "JBL",
    "category": "speakers",
    "price": 28000,
    "originalPrice": 35999,
    "discount": 22,
    "rating": 4.5,
    "reviews": 1256,
    "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": False,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "8",
    "name": "HP Pavilion 15 Laptop",
    "brand": "HP",
    "category": "laptops",
    "price": 135000,
    "originalPrice": 165000,
    "discount": 18,
    "rating": 4.3,
    "reviews": 789,
    "image": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": False,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "9",
    "name": "Xiaomi Smart Robot Vacuum",
    "brand": "Xiaomi",
    "category": "smart-home",
    "price": 56000,
    "originalPrice": 72000,
    "discount": 22,
    "rating": 4.4,
    "reviews": 654,
    "image": "https://images.unsplash.com/photo-1589923188900-85dae523342b?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isNew": True,
    "isHot": False,
    "isBestSeller": False,
  },
  {
    "id": "10",
    "name": "TP-Link Archer AX73 WiFi Router",
    "brand": "TP-Link",
    "category": "networking",
    "price": 18500,
    "originalPrice": 24999,
    "discount": 26,
    "rating": 4.5,
    "reviews": 987,
    "image": "https://images.unsplash.com/photo-1606220838315-056192d5e927?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": False,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "11",
    "name": "Audionic 2.1 Speaker System",
    "brand": "Audionic",
    "category": "speaker-systems",
    "price": 7999,
    "originalPrice": 10999,
    "discount": 27,
    "rating": 4.1,
    "reviews": 445,
    "image": "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": False,
    "isBestSeller": False,
    "isNew": False,
  },
  {
    "id": "12",
    "name": "Samsung Galaxy Watch 7",
    "brand": "Samsung",
    "category": "mobile-accessories",
    "price": 52000,
    "originalPrice": 68000,
    "discount": 24,
    "rating": 4.6,
    "reviews": 1122,
    "image": "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&q=80&w=800",
    "inStock": True,
    "isHot": True,
    "isBestSeller": False,
    "isNew": False,
  }
]

import uuid
for p in products_data:
    uid_str = "00000000-0000-0000-0000-" + p["id"].zfill(12)
    Product.objects.update_or_create(
        id=uuid.UUID(uid_str),
        defaults={
            "name": p["name"],
            "brand": p["brand"],
            "category": p["category"],
            "price": p["price"],
            "originalPrice": p["originalPrice"],
            "discount": p["discount"],
            "rating": p["rating"],
            "reviews": p["reviews"],
            "image": p["image"],
            "inStock": p["inStock"],
            "isBestSeller": p["isBestSeller"],
            "isHot": p["isHot"],
            "isNew": p["isNew"],
            "stock": 10
        }
    )

print("Database seeded with", Product.objects.count(), "products.")
